config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'bookings/new'
  get 'flights/index'
  root 'flights#index'
  resources :passengers
  resources :flights
  resources :bookings
end

app/models/airport.rb
# frozen_string_literal: true

class Airport < ApplicationRecord
  has_many :departing_flights, class_name: 'Flight', foreign_key: 'departure_airport_id'
  has_many :arriving_flights, class_name: 'Flight', foreign_key: 'arrival_airport_id'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
# frozen_string_literal: true

class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers
  accepts_nested_attributes_for :passengers
  validates :flight, presence: true
end

app/models/flight.rb
# frozen_string_literal: true

class Flight < ApplicationRecord
  has_many :bookings

  belongs_to :departure_airport, class_name: 'Airport', foreign_key: 'departure_airport_id', optional: true
  belongs_to :arrival_airport, class_name: 'Airport', foreign_key: 'arrival_airport_id', optional: true

  delegate :code, to: :departure_airport, prefix: true, allow_nil: true
  delegate :code, to: :arrival_airport, prefix: true, allow_nil: true
end

app/models/passenger.rb
# frozen_string_literal: true

class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
# frozen_string_literal: true

class BookingsController < ApplicationController
  before_action :load_flight, only: [:new]
  before_action :load_booking, only: [:show]

  def new
    if params[:flight_id].present?
      @flight = Flight.find(params[:flight_id])
      @passengers = Passenger.all
      @booking = Booking.new(flight_id: params[:flight_id])
    else
      redirect_to flights_path, alert: 'Please select a flight.'
    end
  end

  def create
    @flight = Flight.find(params[:booking][:flight_id])
    @passengers = Passenger.all
    @booking = Booking.new(booking_params)
    @passenger = Passenger.find_by(id: params[:booking][:passenger_id])

    if params[:booking][:flight_id].present? && params[:booking][:passenger_id].present?
      if @booking.save && @passenger
        @booking.passengers << @passenger
        redirect_to booking_path(@booking), notice: 'Booking was successfully created.'
      else
        flash.now[:alert] = 'There was an error while saving the booking.'
        render :new
      end
    else
      flash.now[:alert] = 'Please select a flight and a passenger.'
      render :new
    end
  end

  def show
    @booking = Booking.includes(:flight, :passengers).find_by(id: params[:id])

    return unless @booking.nil?

    redirect_to root_path, alert: 'Booking not found.'
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, :passenger_id)
  end

  def passenger_params
    params.require(:passenger).permit(:name, :email)
  end

  def load_flight
    if params[:flight_id].present? && (flight = Flight.find_by(id: params[:flight_id]))
      @flight = flight
    else
      redirect_to flights_path, alert: 'Please select a flight.'
    end
  end

  def load_booking
    @booking = Booking.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, alert: 'Booking not found.'
  end
end

app/controllers/flights_controller.rb
# frozen_string_literal: true

class FlightsController < ApplicationController
  def index
    if params[:departure_airport_id].present? || params[:arrival_airport_id].present? || params[:start_datetime].present? || params[:passenger_count].present?
      @flights = Flight.all

      if params[:departure_airport_id].present?
        @flights = @flights.where(departure_airport_id: params[:departure_airport_id])
      end

      @flights = @flights.where(arrival_airport_id: params[:arrival_airport_id]) if params[:arrival_airport_id].present?

      @flights = @flights.where('start_datetime >= ?', params[:start_datetime]) if params[:start_datetime].present?

      @flights = @flights.where('passenger_count >= ?', params[:passenger_count]) if params[:passenger_count].present?

      session[:passenger_count] = params[:passenger_count]
    else
      @flights = []
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
# frozen_string_literal: true

module BookingsHelper
end

app/helpers/flights_helper.rb
# frozen_string_literal: true

module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>Booking Details</h1>

<p>Flight ID: <%= @flight.id %></p>
<p>Start Datetime: <%= @flight.start_datetime %></p>
<p>Flight Duration: <%= @flight.flight_duration %>h</p>
<p>Departure Airport Code: <%= @flight.departure_airport.code %></p>
<p>Arrival Airport Code: <%= @flight.arrival_airport.code %></p>

<%= form_with model: @booking, url: bookings_path, local: true do |form| %>
  <%= form.hidden_field :flight_id, value: @flight.id %>

<%= form_with model: @booking, url: bookings_path, local: true do |form| %>
 <%= form.hidden_field :flight_id, value: @flight.id %>

 <p>Passenger:
<%= form.select :passenger_id, options_for_select(@passengers.map { |p| [p.name, p.id] }, @booking.passenger_id), { include_blank: 'Passenger' } %>
</p>

 <p>Emailr:
<%= form.select :passenger_id, options_for_select(@passengers.map { |p| [p.email, p.id] }, @booking.passenger_id), { include_blank: 'Email' } %>
</p>


 <%= form.submit "Confirm Booking" %>
<% end %>

<% end %>

app/views/bookings/show.html.erb
<h1>Booking Details</h1>

<p>Flight ID: <%= @booking.flight.id %></p>
<p>Start Datetime: <%= @booking.flight.start_datetime %></p>
<p>Flight Duration: <%= @booking.flight.flight_duration %>h</p>
<p>Departure Airport Code: <%= @booking.flight.departure_airport.code %></p>
<p>Arrival Airport Code: <%= @booking.flight.arrival_airport.code %></p>

<h2>Passengers</h2>

<% if @booking.passengers.present? %>
    <% @booking.passengers.each do |passenger| %>
  Passenger Name: <%= passenger.name %>
  <br> <br>
  Passenger Email: <%= passenger.email %>
<% end %>

<% else %>
  <p>No passengers selected</p>
<% end %>

app/views/flights/index.html.erb
<h1>Flights</h1>

<%= form_with url: flights_path, method: "get" do |form| %>
  <%= form.select :departure_airport_id, Airport.all.map { |airport| [airport.code, airport.id] }, { include_blank: "Select a departure airport" } %>
  <%= form.select :arrival_airport_id, Airport.all.map { |airport| [airport.code, airport.id] }, { include_blank: "Select an arrival airport" } %>
  <%= form.date_select :start_datetime, discard_day: true, start_year: Date.today.year, end_year: Date.today.year + 1 %>
  <%= form.submit "Search" %>
<% end %>

<% if @flights.any? %>
  <h2>Search Results</h2>
  <%= form_with url: new_booking_path, method: "get" do |form| %>
    <% @flights.each do |flight| %>
      <p>
        <%= form.radio_button :flight_id, flight.id %>
        <%= form.label :flight_id, "Flight ID: #{flight.id}, Start Datetime: #{flight.start_datetime}, Flight Duration: #{flight.flight_duration}, Passenger Count: #{flight.passenger_count}, Departure Airport Code: #{flight.departure_airport_code}, Arrival Airport Code: #{flight.arrival_airport_code}" %>
      </p>
    <% end %>
    <%= form.hidden_field :passenger_count, value: session[:passenger_count] %>
    <%= form.submit "Select Flight" %>
  <% end %>
<% else %>
  <p>Select one of our filters.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>